name: Webpack stats difference
author: William DA SILVA
description: 'Creates a comment in the pull-request comparing two Webpack stats files.'
inputs:
  base_stats_path:
    description: 'Webpack generated "stats.json" file path from the base branch'
    required: true
  head_stats_path:
    description: 'Webpack generated "stats.json" file path from the head branch'
    required: true
  token:
    description: 'Github generated token'
    required: true
  comment_title:
    description: 'Customized GitHub comment title.'
    required: false
  threshold:
    description: 'The minimum percentage increase/decrease in the diff bundle size for a comment to be added. passed directly to Number constructor.'
    required: false
    default: '0'
  extensions:
    description: 'Extensions to filter to, in a comma-delineated string, with or without periods'
    required: false
  all:
    description: If you want to include files that didn't change, set this to 'true'
    required: false
    default: 'false'
branding:
  icon: 'package'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'
