name: Webpack stats difference
author: William DA SILVA
description: 'Creates a comment in the pull-request comparing two Webpack stats files.'
inputs:
  base_stats_path:
    description: 'Webpack generated "stats.json" file path from the base branch'
    required: true
  head_stats_path:
    description: 'Webpack generated "stats.json" file path from the head branch'
    required: true
  token:
    description: 'Github generated token'
    required: true
  comment_title:
    description: 'Customized GitHub comment title.'
    required: false
  announcement_percentage_threshold_increase:
    description: 'The minimum percentage increase in the diff bundle size for a comment to be added. The percentage should use a positive number (integer or floating point) value or zero.'
    required: false
  announcement_percentage_threshold_decrease:
    description: 'The minimum percentage decrease in the diff bundle size for a comment to be added. The percentage should use a negative numeric (integer or floating point) value or zero.'
    required: false
branding:
  icon: 'package'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'
