name: "Chunk difference"
on:
  pull_request:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Diff
      uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base_stats_path: ./demo/base/stats.json
        head_stats_path: ./demo/head/stats.json
        comment_title: 'Above decrease threshold'
        announcement_percentage_threshold_increase: 0
        announcement_percentage_threshold_decrease: -1.6
